version: '3.8'

services:
  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=google_docs
    ports:
      - "5433:5432"
    volumes:
      - db:/data/postgres
    networks:
      - google

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - google
    
  migrate:
    image: migrate/migrate
    networks:
      - google
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-path", "./migrations", "-database", "postgres://postgres:1234@postgres:5432/google_docs?sslmode=disable", "up"]

  userservice:
    container_name: user
    build: .
    ports:
      - "1234:1234"
      - "2345:2345"
    networks:
     - google
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_started
      redis:
        condition: service_healthy

  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=photos
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://3.65.0.245:9000/minio/health/live || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - google

networks:
  google:

volumes:
  db:
  minio_data:
