name: API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Check if the directory exists
            if [ -d "GoogleDocs" ]; then
              echo "Directory exists. Pulling latest changes..."
              cd GoogleDocs
              git pull
            else
              echo "Directory does not exist. Cloning repository..."
              mkdir GoogleDocs
              cd GoogleDocs
              git clone git@github.com:Ozodbek2129/google_docs_UserService.git
            fi

            # Stop and remove existing Docker containers
            docker compose down

            # Build and start Docker containers
            docker compose up -d

