name: API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # Bu yerda environment to'g'ri ishlatilgan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: go mod download

      - name: Run Redis Tests
        run: go test -v ./storage/redis/redis_test.go

      - name: Run User Tests
        run: go test -v ./storage/postgres/user_test.go

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ -d "Google_docs" ]; then
              echo "Directory exists. Pulling latest changes..."
              cd Google_docs/google_docs_UserService
              git pull
            else
              echo "Directory does not exist. Cloning repository..."
              mkdir Google_docs
              cd Google_docs
              git clone git@github.com:Ozodbek2129/google_docs_UserService.git
            fi

            docker compose down
            docker compose up -d --build
